//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpConnectionsViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TcpConnectionsViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;n&quot;:&quot;reserved&quot;,&quot;p&quot;:0,&quot;d&quot;:&quot;Reserved&quot;},{&quot;n&quot;:&quot;tcpmux&quot;,&quot;p&quot;:1,&quot;d&quot;:&quot;TCP Port Service Multiplexer&quot;},{&quot;n&quot;:&quot;compressnet&quot;,&quot;p&quot;:2,&quot;d&quot;:&quot;Management Utility&quot;},{&quot;n&quot;:&quot;compressnet&quot;,&quot;p&quot;:3,&quot;d&quot;:&quot;Compression Process&quot;},{&quot;n&quot;:&quot;unassigned&quot;,&quot;p&quot;:4,&quot;d&quot;:&quot;Unassigned&quot;},{&quot;n&quot;:&quot;rje&quot;,&quot;p&quot;:5,&quot;d&quot;:&quot;Remote Job Entry&quot;},{&quot;n&quot;:&quot;unassigned&quot;,&quot;p&quot;:6,&quot;d&quot;:&quot;Unassigned&quot;},{&quot;n&quot;:&quot;echo&quot;,&quot;p&quot;:7,&quot;d&quot;:&quot;Echo&quot;},{&quot;n&quot;:&quot;unassigned&quot;,&quot;p&quot;:8,&quot;d&quot;:&quot;Unassigned&quot;},{&quot;n&quot;:&quot;discard&quot;,&quot;p&quot;:9,&quot;d&quot;:&quot;Discard&quot;},{&quot;n&quot;:&quot;discard&quot;,&quot;p&quot;:9,&quot;d&quot;:&quot;Discard&quot;},{&qu....
        /// </summary>
        internal static string CommonServices {
            get {
                return ResourceManager.GetString("CommonServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;p&quot;:&quot;000000&quot;,&quot;n&quot;:&quot;Officially Xerox but 000000 is more common&quot;},{&quot;p&quot;:&quot;000001&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000002&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000003&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000004&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000005&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000006&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000007&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000008&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;000009&quot;,&quot;n&quot;:&quot;XEROX CORPORATION&quot;},{&quot;p&quot;:&quot;00000A&quot;,&quot;n&quot;:&quot;OMRON TATEISI ELECTRONICS CO.&quot;},{&quot;p&quot;:&quot;00000B&quot;,&quot;n&quot;:&quot;MATRIX CORPORATION&quot;},{&quot;p&quot;: [rest of string wa....
        /// </summary>
        internal static string KnownMacManufacturers {
            get {
                return ResourceManager.GetString("KnownMacManufacturers", resourceCulture);
            }
        }
    }
}
