//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TcpConnectionsViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalAddressIsDisplayed {
            get {
                return ((bool)(this["LocalAddressIsDisplayed"]));
            }
            set {
                this["LocalAddressIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalHostnameIsDisplayed {
            get {
                return ((bool)(this["LocalHostnameIsDisplayed"]));
            }
            set {
                this["LocalHostnameIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalPortIsDisplayed {
            get {
                return ((bool)(this["LocalPortIsDisplayed"]));
            }
            set {
                this["LocalPortIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LocalPortCommonNameIsDisplayed {
            get {
                return ((bool)(this["LocalPortCommonNameIsDisplayed"]));
            }
            set {
                this["LocalPortCommonNameIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LocalPortCommonDescriptionIsDisplayed {
            get {
                return ((bool)(this["LocalPortCommonDescriptionIsDisplayed"]));
            }
            set {
                this["LocalPortCommonDescriptionIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StateIsDisplayed {
            get {
                return ((bool)(this["StateIsDisplayed"]));
            }
            set {
                this["StateIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteAddressIsDisplayed {
            get {
                return ((bool)(this["RemoteAddressIsDisplayed"]));
            }
            set {
                this["RemoteAddressIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteMacAddressIsDisplayed {
            get {
                return ((bool)(this["RemoteMacAddressIsDisplayed"]));
            }
            set {
                this["RemoteMacAddressIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteMacAddressManufacturerIsDisplayed {
            get {
                return ((bool)(this["RemoteMacAddressManufacturerIsDisplayed"]));
            }
            set {
                this["RemoteMacAddressManufacturerIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteHostnameIsDisplayed {
            get {
                return ((bool)(this["RemoteHostnameIsDisplayed"]));
            }
            set {
                this["RemoteHostnameIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemotePortIsDisplayed {
            get {
                return ((bool)(this["RemotePortIsDisplayed"]));
            }
            set {
                this["RemotePortIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemotePortCommonNameIsDisplayed {
            get {
                return ((bool)(this["RemotePortCommonNameIsDisplayed"]));
            }
            set {
                this["RemotePortCommonNameIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemotePortCommonDescriptionIsDisplayed {
            get {
                return ((bool)(this["RemotePortCommonDescriptionIsDisplayed"]));
            }
            set {
                this["RemotePortCommonDescriptionIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteCountryIsDisplayed {
            get {
                return ((bool)(this["RemoteCountryIsDisplayed"]));
            }
            set {
                this["RemoteCountryIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RemoteIspIsDisplayed {
            get {
                return ((bool)(this["RemoteIspIsDisplayed"]));
            }
            set {
                this["RemoteIspIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteTimezoneIsDisplayed {
            get {
                return ((bool)(this["RemoteTimezoneIsDisplayed"]));
            }
            set {
                this["RemoteTimezoneIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteAreaCodeIsDisplayed {
            get {
                return ((bool)(this["RemoteAreaCodeIsDisplayed"]));
            }
            set {
                this["RemoteAreaCodeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteAsnIsDisplayed {
            get {
                return ((bool)(this["RemoteAsnIsDisplayed"]));
            }
            set {
                this["RemoteAsnIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteContinentCodeIsDisplayed {
            get {
                return ((bool)(this["RemoteContinentCodeIsDisplayed"]));
            }
            set {
                this["RemoteContinentCodeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteLongitudeIsDisplayed {
            get {
                return ((bool)(this["RemoteLongitudeIsDisplayed"]));
            }
            set {
                this["RemoteLongitudeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteLatitudeIsDisplayed {
            get {
                return ((bool)(this["RemoteLatitudeIsDisplayed"]));
            }
            set {
                this["RemoteLatitudeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteCountryCodeIsDisplayed {
            get {
                return ((bool)(this["RemoteCountryCodeIsDisplayed"]));
            }
            set {
                this["RemoteCountryCodeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteCountryCode3IsDisplayed {
            get {
                return ((bool)(this["RemoteCountryCode3IsDisplayed"]));
            }
            set {
                this["RemoteCountryCode3IsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessIdIsDisplayed {
            get {
                return ((bool)(this["ProcessIdIsDisplayed"]));
            }
            set {
                this["ProcessIdIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessCaptionIsDisplayed {
            get {
                return ((bool)(this["ProcessCaptionIsDisplayed"]));
            }
            set {
                this["ProcessCaptionIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessOwnerIsDisplayed {
            get {
                return ((bool)(this["ProcessOwnerIsDisplayed"]));
            }
            set {
                this["ProcessOwnerIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcessCreationDateIsDisplayed {
            get {
                return ((bool)(this["ProcessCreationDateIsDisplayed"]));
            }
            set {
                this["ProcessCreationDateIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcessExecutablePathIsDisplayed {
            get {
                return ((bool)(this["ProcessExecutablePathIsDisplayed"]));
            }
            set {
                this["ProcessExecutablePathIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcessCommandLineIsDisplayed {
            get {
                return ((bool)(this["ProcessCommandLineIsDisplayed"]));
            }
            set {
                this["ProcessCommandLineIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RemoteDmaCodeIsDisplayed {
            get {
                return ((bool)(this["RemoteDmaCodeIsDisplayed"]));
            }
            set {
                this["RemoteDmaCodeIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimeSinceProcessCreationIsDisplayed {
            get {
                return ((bool)(this["TimeSinceProcessCreationIsDisplayed"]));
            }
            set {
                this["TimeSinceProcessCreationIsDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webmooch.net/LinkToLatestTcpConnectionsViewerVersionData")]
        public string StaticVersionUri {
            get {
                return ((string)(this["StaticVersionUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://webmooch.net/RedirectToTcpConnectionsViewerHome.html")]
        public string ProjectHomepageUri {
            get {
                return ((string)(this["ProjectHomepageUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support@webmooch.net")]
        public string CrashEmailAddress {
            get {
                return ((string)(this["CrashEmailAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pending")]
        public string AsyncPropertyPendingText {
            get {
                return ((string)(this["AsyncPropertyPendingText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("loading")]
        public string AsyncPropertyLoadingText {
            get {
                return ((string)(this["AsyncPropertyLoadingText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EEEEEE")]
        public string AsyncPropertyPendingTextColour {
            get {
                return ((string)(this["AsyncPropertyPendingTextColour"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CCCCCC")]
        public string AsyncPropertyLoadingTextColour {
            get {
                return ((string)(this["AsyncPropertyLoadingTextColour"]));
            }
        }
    }
}
